import time

def loading():
    print("\rL |", end=' ')
    time.sleep(0.15)
    print("\rLo /", end=' ')
    time.sleep(0.15)
    print("\rLoa -", end=' ')
    time.sleep(0.15)
    print("\rLoad \\", end=' ')
    time.sleep(0.15)
    print("\rLoadi |", end=' ')
    time.sleep(0.15)
    print("\rLoadin /", end=' ')
    time.sleep(0.15)
    print("\rLoading -", end=' ')
    time.sleep(0.15)

    for i in range(3):
        print("\rLoading \\", end=' ')
        time.sleep(0.25)
        print("\rLoading |", end=' ')
        time.sleep(0.25)
        print("\rLoading /", end=' ')
        time.sleep(0.25)
        print("\rLoading -", end=' ')
        time.sleep(0.25)

    print("\rLoading ->", end=' ')
    time.sleep(0.15)
    print("\rLoading -> C", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Co", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Com", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Comp", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Compr", end='  ')
    time.sleep(0.15)
    print("\rLoading -> Comp", end='  ')
    time.sleep(0.15)
    print("\rLoading -> Compl", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Comple", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Complet", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Complete", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Completed", end=' ')
    time.sleep(0.15)
    print("\rLoading -> Completed!\n")
    time.sleep(0.15)    